// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: api/proto/basket.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasketRequest) Reset() {
	*x = GetBasketRequest{}
	mi := &file_api_proto_basket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketRequest) ProtoMessage() {}

func (x *GetBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketRequest.ProtoReflect.Descriptor instead.
func (*GetBasketRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_proto_rawDescGZIP(), []int{0}
}

func (x *GetBasketRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_api_proto_basket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_api_proto_basket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateItemRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateItemRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_api_proto_basket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveItemRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveItemRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ClearBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBasketRequest) Reset() {
	*x = ClearBasketRequest{}
	mi := &file_api_proto_basket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBasketRequest) ProtoMessage() {}

func (x *ClearBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBasketRequest.ProtoReflect.Descriptor instead.
func (*ClearBasketRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_proto_rawDescGZIP(), []int{4}
}

func (x *ClearBasketRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Basket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*BasketItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Basket) Reset() {
	*x = Basket{}
	mi := &file_api_proto_basket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Basket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basket) ProtoMessage() {}

func (x *Basket) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basket.ProtoReflect.Descriptor instead.
func (*Basket) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_proto_rawDescGZIP(), []int{5}
}

func (x *Basket) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Basket) GetItems() []*BasketItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Basket) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Basket) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BasketItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasketItem) Reset() {
	*x = BasketItem{}
	mi := &file_api_proto_basket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketItem) ProtoMessage() {}

func (x *BasketItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketItem.ProtoReflect.Descriptor instead.
func (*BasketItem) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_proto_rawDescGZIP(), []int{6}
}

func (x *BasketItem) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *BasketItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *BasketItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BasketItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ClearBasketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBasketResponse) Reset() {
	*x = ClearBasketResponse{}
	mi := &file_api_proto_basket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBasketResponse) ProtoMessage() {}

func (x *ClearBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_basket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBasketResponse.ProtoReflect.Descriptor instead.
func (*ClearBasketResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_basket_proto_rawDescGZIP(), []int{7}
}

func (x *ClearBasketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_basket_proto protoreflect.FileDescriptor

const file_api_proto_basket_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/basket.proto\x12\x06basket\"+\n" +
	"\x10GetBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"d\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"g\n" +
	"\x11UpdateItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"K\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\"-\n" +
	"\x12ClearBasketRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\x80\x01\n" +
	"\x06Basket\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.basket.BasketItemR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"q\n" +
	"\n" +
	"BasketItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"/\n" +
	"\x13ClearBasketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbd\x02\n" +
	"\rBasketService\x127\n" +
	"\tGetBasket\x12\x18.basket.GetBasketRequest\x1a\x0e.basket.Basket\"\x00\x123\n" +
	"\aAddItem\x12\x16.basket.AddItemRequest\x1a\x0e.basket.Basket\"\x00\x129\n" +
	"\n" +
	"UpdateItem\x12\x19.basket.UpdateItemRequest\x1a\x0e.basket.Basket\"\x00\x129\n" +
	"\n" +
	"RemoveItem\x12\x19.basket.RemoveItemRequest\x1a\x0e.basket.Basket\"\x00\x12H\n" +
	"\vClearBasket\x12\x1a.basket.ClearBasketRequest\x1a\x1b.basket.ClearBasketResponse\"\x00B\x13Z\x11gomicro/api/protob\x06proto3"

var (
	file_api_proto_basket_proto_rawDescOnce sync.Once
	file_api_proto_basket_proto_rawDescData []byte
)

func file_api_proto_basket_proto_rawDescGZIP() []byte {
	file_api_proto_basket_proto_rawDescOnce.Do(func() {
		file_api_proto_basket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_basket_proto_rawDesc), len(file_api_proto_basket_proto_rawDesc)))
	})
	return file_api_proto_basket_proto_rawDescData
}

var file_api_proto_basket_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_basket_proto_goTypes = []any{
	(*GetBasketRequest)(nil),    // 0: basket.GetBasketRequest
	(*AddItemRequest)(nil),      // 1: basket.AddItemRequest
	(*UpdateItemRequest)(nil),   // 2: basket.UpdateItemRequest
	(*RemoveItemRequest)(nil),   // 3: basket.RemoveItemRequest
	(*ClearBasketRequest)(nil),  // 4: basket.ClearBasketRequest
	(*Basket)(nil),              // 5: basket.Basket
	(*BasketItem)(nil),          // 6: basket.BasketItem
	(*ClearBasketResponse)(nil), // 7: basket.ClearBasketResponse
}
var file_api_proto_basket_proto_depIdxs = []int32{
	6, // 0: basket.Basket.items:type_name -> basket.BasketItem
	0, // 1: basket.BasketService.GetBasket:input_type -> basket.GetBasketRequest
	1, // 2: basket.BasketService.AddItem:input_type -> basket.AddItemRequest
	2, // 3: basket.BasketService.UpdateItem:input_type -> basket.UpdateItemRequest
	3, // 4: basket.BasketService.RemoveItem:input_type -> basket.RemoveItemRequest
	4, // 5: basket.BasketService.ClearBasket:input_type -> basket.ClearBasketRequest
	5, // 6: basket.BasketService.GetBasket:output_type -> basket.Basket
	5, // 7: basket.BasketService.AddItem:output_type -> basket.Basket
	5, // 8: basket.BasketService.UpdateItem:output_type -> basket.Basket
	5, // 9: basket.BasketService.RemoveItem:output_type -> basket.Basket
	7, // 10: basket.BasketService.ClearBasket:output_type -> basket.ClearBasketResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_basket_proto_init() }
func file_api_proto_basket_proto_init() {
	if File_api_proto_basket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_basket_proto_rawDesc), len(file_api_proto_basket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_basket_proto_goTypes,
		DependencyIndexes: file_api_proto_basket_proto_depIdxs,
		MessageInfos:      file_api_proto_basket_proto_msgTypes,
	}.Build()
	File_api_proto_basket_proto = out.File
	file_api_proto_basket_proto_goTypes = nil
	file_api_proto_basket_proto_depIdxs = nil
}
